
install(TARGETS ${PROJECT_NAME}
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Testing
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Dependencies
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})
install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/CMake
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.txt
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})

install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/CMake/templates/installing.cmake
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME}/CMake/
        RENAME packaging.cmake)

install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Library
        DESTINATION ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME})

install(CODE "execute_process(COMMAND
  python ${CMAKE_CURRENT_SOURCE_DIR}/CMake/build_info.py ${PROJECT_NAME} ${PROJECT_VERSION} OUTPUT_VARIABLE build_info)
  file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME}/build_info.txt \${build_info})")

install(CODE "file(ARCHIVE_CREATE OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}.zip
        PATHS ${CMAKE_CURRENT_BINARY_DIR}/packaging/${PROJECT_NAME}/
        FORMAT zip
        )")